[
    {
        "function_name": "forceSend",
        "code": "function forceSend() external onlyOwner { (bool success,) = address(feeWallet).call{value : address(this).balance}(\"\"); success = false; }",
        "vulnerability": "Potential loss of funds due to unchecked call result",
        "reason": "The function uses a low-level call to send the contract's balance to the feeWallet address. The result of the call is not properly checked for success, as the assignment of 'success = false;' immediately after the call nullifies any check. This can lead to funds being lost if the call fails, as the transaction would not revert in such a case, and the owner would not be alerted to the failure.",
        "file_name": "0x0d95bc0c758ae70141fc95345a7164a4c6e1df15.sol"
    },
    {
        "function_name": "forceSwap",
        "code": "function forceSwap() external onlyOwner { _swapTokensForEth(balanceOf(address(this))); (bool success,) = address(feeWallet).call{value : address(this).balance}(\"\"); success = false; }",
        "vulnerability": "Potential loss of funds due to unchecked call result",
        "reason": "Similar to the forceSend function, this function performs a low-level call to transfer the contract's ETH balance to the feeWallet. The result of the call is not properly checked for success, and the immediate assignment of 'success = false;' negates any error handling. This could result in loss of funds if the call fails, as there would be no transaction revert and no notification of failure.",
        "file_name": "0x0d95bc0c758ae70141fc95345a7164a4c6e1df15.sol"
    },
    {
        "function_name": "_transfer",
        "code": "function _transfer( address from, address to, uint256 amount ) internal override { require(from != address(0), \"ERC20: transfer from the zero address\"); require(to != address(0), \"ERC20: transfer to the zero address\"); require(!_isBlacklisted[from], \"Your address has been marked as a sniper, you are unable to transfer or swap.\"); if (amount == 0) { super._transfer(from, to, 0); return; } if(tradingActive) { require(block.number >= _launchBlock + deadBlocks, \"NOT BOT\"); } if (limitsInEffect) { if ( from != owner() && to != owner() && to != address(0) && to != address(0xdead) && !_swapping ) { if (!tradingActive) { require(_isExcludedFromFees[from] || _isExcludedFromFees[to], \"Trading is not active.\"); } if (balanceOf(to) == 0 && _holderFirstBuyTimestamp[to] == 0) { _holderFirstBuyTimestamp[to] = block.timestamp; } if (transferDelayEnabled) { if (to != owner() && to != address(uniswapV2Router) && to != address(uniswapV2Pair)) { require(_holderLastTransferTimestamp[tx.origin] < block.number, \"_transfer:: Transfer Delay enabled. Only one purchase per block allowed.\"); _holderLastTransferTimestamp[tx.origin] = block.number; } } if (automatedMarketMakerPairs[from] && !_isExcludedMaxTransactionAmount[to]) { require(amount <= maxTransactionAmount, \"Buy transfer amount exceeds the maxTransactionAmount.\"); require(amount + balanceOf(to) <= maxWallet, \"Max wallet exceeded\"); } else if (automatedMarketMakerPairs[to] && !_isExcludedMaxTransactionAmount[from]) { require(amount <= maxTransactionAmount, \"Sell transfer amount exceeds the maxTransactionAmount.\"); } else if (!_isExcludedMaxTransactionAmount[to]) { require(amount + balanceOf(to) <= maxWallet, \"Max wallet exceeded\"); } } } uint256 contractTokenBalance = balanceOf(address(this)); bool canSwap = contractTokenBalance >= swapTokensAtAmount; if ( canSwap && !_swapping && !automatedMarketMakerPairs[from] && !_isExcludedFromFees[from] && !_isExcludedFromFees[to] ) { _swapping = true; swapBack(); _swapping = false; } bool takeFee = !_swapping; if (_isExcludedFromFees[from] || _isExcludedFromFees[to]) { takeFee = false; } uint256 fees = 0; if (takeFee) { fees = amount.mul(totalFees).div(100); _tokensForLiquidity += fees * _liquidityFee / totalFees; _tokensForMarketing += fees * _marketingFee / totalFees; if (fees > 0) { super._transfer(from, address(this), fees); } amount -= fees; } super._transfer(from, to, amount); }",
        "vulnerability": "Potential front-running attack due to trading restrictions",
        "reason": "The function imposes restrictions on trading activity, such as max transaction amounts and transfer delays, which are enforced when limitsInEffect is true. These restrictions could potentially be exploited by attackers who front-run transactions to ensure they are not subject to these limits, especially if the limits are lifted at a later time. Additionally, the initial restriction of trading only being allowed after a certain number of blocks (deadBlocks) opens up the potential for manipulative practices during the early stages of trading.",
        "file_name": "0x0d95bc0c758ae70141fc95345a7164a4c6e1df15.sol"
    }
]